apiVersion: v1
kind: Pod
metadata:
  name: riddle6-other-pod
  namespace: riddle6-other
spec:
  containers:
    - name: curl-container
      image: curlimages/curl:latest
      command:
        - "sh"
        - "-c"
        - "curl riddle6-service:80 || echo 'Service not found'"
