apiVersion: v1
kind: Pod
metadata:
  name: riddle5-pod
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "non-existent-label"
            operator: In
            values:
              - "impossible-value"
  containers:
  - name: busybox
    image: busybox:latest
    command: ["sleep", "3600"]
